#default directory if not specified at runtime
target_directory: './Files/Downloads'
#delete duplicate files when moving or archiving files
delete_redundant_files: true
#delete duplicate files that match duplicate patterns like (1), (2), (copy), etc.
delete_duplicate_files: true
#rename files that match duplicate patterns like (1), (2), (copy), etc. but which do not have an original file
rename_orphaned_duplicates: true
